default_platform(:ios)

platform :ios do

  desc "Commit new certificates and provisioning profiles to Git if necessary. Only an itunesconnect admin can run this lane."
  lane :update_certificates do
    match(
      type: "appstore"
    )
  end

  lane :beta_ci do
    increment_build_number(
      build_number: ENV["GITHUB_RUN_ID"]
    )
    increment_version_number(
      version_number: ENV["VERSION_NUMBER"]
    )
    create_keychain(
      name: "Fastlane_CI",
      password: "CI_Password",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    match(
      type: "appstore", 
      readonly: true, 
      keychain_name: 'Fastlane_CI', 
      keychain_password: 'CI_Password',
      username: ENV["APPLE_USERNAME"],
      git_url: ENV["GIT_CERT_HTTPS_URL"]
    )
    build_app(
      project: "SimpleTest.xcodeproj", 
      scheme: "SimpleTest - Staging"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true, 
      apple_id: ENV["APP_APPLE_ID"],
      username: ENV["APPLE_USERNAME"]
    )
  end

  lane :release_ci do
    increment_build_number(
      build_number: ENV["GITHUB_RUN_ID"]
    )
    increment_version_number(
      version_number: ENV["VERSION_NUMBER"]
    )
    create_keychain(
      name: "Fastlane_CI",
      password: "CI_Password",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    match(
      type: "appstore", 
      readonly: true, 
      keychain_name: 'Fastlane_CI', 
      keychain_password: 'CI_Password',
      username: ENV["APPLE_USERNAME"],
      git_url: ENV["GIT_CERT_HTTPS_URL"]
    )
    build_app(
      project: "SimpleTest.xcodeproj", 
      scheme: "SimpleTest"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true, 
      apple_id: ENV["APP_APPLE_ID"],
      username: ENV["APPLE_USERNAME"]
    )
  end
  
end
