name: Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Install Fastlane
      run: bundle install
    - name: Upload to Testflight
      run: bundle exec fastlane ios beta
