name: TestFlight

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Fastlane
        run: |
          bundle update --bundler
          bundle install
      - name: Set Appstore Connect User
        run: bundle exec fastlane fastlane-credentials add --username thurber.carlos@gmail.com --password ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      - name: Set release version
        run: echo ::set-env name=VERSION_NUMBER::$(echo ${GITHUB_REF#refs/*/v})
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.6.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Build and Upload to Testflight
        run: bundle exec fastlane beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.KEYSTORE_PASSPHRASE }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
