name: TestFlight

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Fastlane
        run: bundle install
      - name: Set Appstore Connect User
        run: bundle exec fastlane fastlane-credentials add --username thurber.carlos@gmail.com --password ${{ secrets.APPSTORE_PASSWORD }}
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/*/v})
      - name: Set build version
        run: bundle exec fastlane run increment_version_number version_number:"${{ env.RELEASE_VERSION }}"
      - name: Fastlane Beta CI
        run: bundle exec fastlane beta_ci
        env:
          MATCH_PASSWORD: ${{ secrets.KEYSTORE_PASSPHRASE }}
          FASTLANE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
